source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!

workspace 'StepikIOS'

xcodeproj 'StepikIOS.xcodeproj'
xcodeproj 'Common/StepikCore/StepikCore.xcodeproj'
xcodeproj 'Features/ExternalWorkers/ExternalWorkers.xcodeproj'

def net_pods
    pod 'Alamofire', '~> 4.7.2'
end

def ui_pods
    pod 'KRPullLoader'
    pod 'EmptyDataSet-Swift', '~> 4.0.4'
end

target :StepikIOS do
   xcodeproj 'StepikIOS.xcodeproj'
   ui_pods
   net_pods 
end

target :ExternalWorkers do
	xcodeproj 'Features/ExternalWorkers/ExternalWorkers.xcodeproj'
    net_pods
end

target :ExternalWorkersTests do
    xcodeproj 'Features/ExternalWorkers/ExternalWorkers.xcodeproj'
    net_pods
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '4.0'
        end
    end
end
